### ISSUE TITLE
Augment NextStudio component to accept types

### ISSUE THREAD

**Issue by amorfati254** [saiichihashimoto/sanity-typed#116]
when passing config created by this library the <NextStudio /> component complains while it works when using the plain sanity define functions.
```jsx
<NextStudio config={config} />
```

**Comment by saiichihashimoto** [comment]
@amorfati254 can you include the error? Something that shows the issue that occurs?

**Comment by amorfati254** [comment]
@saiichihashimoto this is the error its pretty long.
Type 'Config<Type<"document", "media", keyof IntrinsicDefinitions<any, any, any, any>, StrictDefinition, (FieldDefinitionBase & Omit<...> & { ...; }) | (FieldDefinitionBase & ... 1 more ... & { ...; }) | (FieldDefinitionBase & ... 1 more ... & { ...; }) | (FieldDefinitionBase & ... 1 more ... & { ...; }), DefinitionBase<....' is not assignable to type 'Config'.
  Type '{ basePath: string; subtitle?: string | undefined; logo?: ComponentType | undefined; icon?: ComponentType | undefined; theme?: StudioTheme | undefined; ... 13 more ...; schema?: { ...; } | undefined; }[]' is not assignable to type 'Config'.
    Type '{ basePath: string; subtitle?: string | undefined; logo?: ComponentType | undefined; icon?: ComponentType | undefined; theme?: StudioTheme | undefined; ... 13 more ...; schema?: { ...; } | undefined; }[]' is not assignable to type 'WorkspaceOptions[]'.
      Type '{ basePath: string; subtitle?: string | undefined; logo?: ComponentType | undefined; icon?: ComponentType | undefined; theme?: StudioTheme | undefined; ... 13 more ...; schema?: { ...; } | undefined; }' is not assignable to type 'WorkspaceOptions'.
        Types of property 'plugins' are incompatible.
          Type '(PluginOptions | PluginOptions<Type<any, any, any, any, any, any>, any>)[] | undefined' is not assignable to type 'PluginOptions[] | undefined'.
            Type '(PluginOptions | PluginOptions<Type<any, any, any, any, any, any>, any>)[]' is not assignable to type 'PluginOptions[]'.
              Type 'PluginOptions | PluginOptions<Type<any, any, any, any, any, any>, any>' is not assignable to type 'PluginOptions'.
                Type 'PluginOptions<Type<any, any, any, any, any, any>, any>' is not assignable to type 'PluginOptions'.
                  Types of property 'schema' are incompatible.
                    Type '{ name?: string | undefined; templates?: Template<any, any>[] | TemplateResolver | undefined; types?: Type<any, any, any, any, any, any>[] | ComposableOption<...> | undefined; } | undefined' is not assignable to type 'SchemaPluginOptions | undefined'.
                      Type '{ name?: string | undefined; templates?: Template<any, any>[] | TemplateResolver | undefined; types?: Type<any, any, any, any, any, any>[] | ComposableOption<...> | undefined; }' is not assignable to type 'SchemaPluginOptions'.
                        Types of property 'types' are incompatible.
                          Type 'Type<any, any, any, any, any, any>[] | ComposableOption<Type<any, any, any, any, any, any>[], Omit<ConfigContext, "schema" | "client" | "currentUser" | "getClient">> | undefined' is not assignable to type 'SchemaTypeDefinition[] | ComposableOption<SchemaTypeDefinition[], Omit<ConfigContext, "schema" | "client" | "currentUser" | "getClient">> | undefined'.
                            Type 'Type<any, any, any, any, any, any>[]' is not assignable to type 'SchemaTypeDefinition[] | ComposableOption<SchemaTypeDefinition[], Omit<ConfigContext, "schema" | "client" | "currentUser" | "getClient">> | undefined'.
                              Type 'Type<any, any, any, any, any, any>[]' is not assignable to type 'SchemaTypeDefinition[]'.
                                Type 'Type<any, any, any, any, any, any>' is not assignable to type 'SchemaTypeDefinition'.
                                  Type 'Omit<{ type: "string"; options?: StringOptions | undefined; placeholder?: string | undefined; initialValue?: InitialValueProperty<any, string>; ... 8 more ...; validation?: ValidationBuilder<...> | undefined; }, "FIXME why does this fail without the omit? we're clearly not using it"> & { ...; }' is not assignable to type 'SchemaTypeDefinition'.
                                    Type 'Omit<{ type: "string"; options?: StringOptions | undefined; placeholder?: string | undefined; initialValue?: InitialValueProperty<any, string>; ... 8 more ...; validation?: ValidationBuilder<...> | undefined; }, "FIXME why does this fail without the omit? we're clearly not using it"> & { ...; }' is not assignable to type 'TypeAliasDefinition<string, "string" | "number" | "boolean" | "object" | "image" | "text" | "date" | "email" | "file" | "url" | "document" | "array" | "block" | "crossDatasetReference" | "datetime" | "geopoint" | "reference" | "slug">'.
                                      Types of property 'validation' are incompatible.
                                        Type 'ValidationBuilder<any, string, StringRule> | undefined' is not assignable to type 'SchemaValidationValue'.
                                          Type 'ValidationBuilder<any, string, StringRule>' is not assignable to type 'SchemaValidationValue'.
                                            Type 'ValidationBuilder<any, string, StringRule>' is not assignable to type '(rule: Rule) => SchemaValidationValue'.
                                              Types of parameters 'rule' and 'rule' are incompatible.
                                                Property '[requiredSymbol]' is missing in type 'Rule' but required in type '{ min: (minNumber: number | FieldReference) => ...; max: (maxNumber: number | FieldReference) => ...; length: (exactLength: number | FieldReference) => ...; ... 9 more ...; [requiredSymbol]: false; }'.ts(2322)
index.d.ts(21, 5): '[requiredSymbol]' is declared here.
index.d.ts(8882, 3): The expected type comes from property 'config' which is declared here on type 'IntrinsicAttributes & NextStudioProps'

**Comment by saiichihashimoto** [comment]
Got it, so this is mostly an issue that the type returned by `defineConfig` is different in `sanity` and `@sanity-typed/types` and `NextStudio` is expecting the type from `sanity`.

We should augment the type of `NextStudio` to accept the types returned by `@sanity-typed/types` but, also, we should have some kind of escape hatch for this library to re-un-type the configs to fit in places that accept them, so we don't have to do this for each thing.

**Comment by saiichihashimoto** [comment]
@amorfati254, which package are you importing from? https://github.com/sanity-io/next-sanity?

**Comment by amorfati254** [comment]
@saiichihashimoto yes am using the next-sanity package. My studio page is as follows: 
```ts
"use client";

/**
 * This route is responsible for the built-in authoring environment using Sanity Studio.
 * All routes under your studio path is handled by this file using Next.js' catch-all routes:
 * https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes
 *
 * You can learn more about the next-sanity package here:
 * https://github.com/sanity-io/next-sanity
 */
import config from "@/sanity.config";
import { NextStudio } from "next-sanity/studio";

export default function StudioPage() {
  //@ts-ignore
  return <NextStudio config={config} />;
}
```

**Comment by amorfati254** [comment]
@saiichihashimoto I have encountered the same issue when working with the `@portabletext/react@latest` package. 
code sample
```tsx
<PortableText value={post.body} />
```
it gives the following TSError: 
```
Type '(({ children: ({ [x: string]: any; _type: string; _key?: string | undefined; } | { _type: "span"; _key?: string | undefined; text: string; marks?: string[] | undefined; })[]; markDefs?: ({ [x: string]: unknown; [x: number]: unknown; } & { ...; })[] | undefined; style?: string | undefined; listItem?: string | undefin...' is not assignable to type 'TypedObject | TypedObject[]'.
  Type '(({ children: ({ [x: string]: any; _type: string; _key?: string | undefined; } | { _type: "span"; _key?: string | undefined; text: string; marks?: string[] | undefined; })[]; markDefs?: ({ [x: string]: unknown; [x: number]: unknown; } & { ...; })[] | undefined; style?: string | undefined; listItem?: string | undefin...' is not assignable to type 'TypedObject[]'.
    Type '({ children: ({ [x: string]: any; _type: string; _key?: string | undefined; } | { _type: "span"; _key?: string | undefined; text: string; marks?: string[] | undefined; })[]; markDefs?: ({ [x: string]: unknown; [x: number]: unknown; } & { ...; })[] | undefined; style?: string | undefined; listItem?: string | undefine...' is not assignable to type 'TypedObject'.
      Type '{ alt?: string | undefined; asset?: { _type: string; _ref: string; _key?: string | undefined; _weak?: boolean | undefined; _strengthenOnPublish?: { type: string; weak?: boolean | undefined; template?: { ...; } | undefined; } | undefined; } | undefined; crop?: { ...; } | undefined; hotspot?: { ...; } | undefined; } &...' is not assignable to type 'TypedObject'.
        Types of property '_type' are incompatible.
          Type 'unknown' is not assignable to type 'string'.
```
However, I think this might be due to @sanity-typed not including the `_type` field for fields.

my post sanity schema is as follows: 
```ts
export default defineType({
  name: "post",
  title: "Post",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "title",
        maxLength: 96,
      },
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "reference",
      to: { type: "author" },
    }),
    defineField({
      name: "mainImage",
      title: "Main image",
      type: "image",
      options: {
        hotspot: true,
      },
      fields: [
        defineField({
          name: "alt",
          type: "string",
          title: "Alternative Text",
        }),
      ],
    }),
    defineField({
      name: "categories",
      title: "Categories",
      type: "array",
      of: [defineArrayMember({ type: "reference", to: { type: "category" } })],
    }),
    defineField({
      name: "publishedAt",
      title: "Published at",
      type: "datetime",
    }),
    //defined in another file
    defineField({
      name: "body",
      title: "Body",
      type: "blockContent",
    }),
  ],

  preview: {
    select: {
      title: "title",
      author: "author.name",
      media: "mainImage",
    },
    prepare(selection) {
      const { author } = selection;
      return { ...selection, subtitle: author && `by ${author}` };
    },
  },
});
```
and my blockContent schema is as follows: 
```ts
export default defineType({
  title: "Block Content",
  name: "blockContent",
  type: "array",
  of: [
    defineArrayMember({
      title: "Block",
      type: "block",
      styles: [
        { title: "Normal", value: "normal" },
        { title: "H1", value: "h1" },
        { title: "H2", value: "h2" },
        { title: "H3", value: "h3" },
        { title: "H4", value: "h4" },
        { title: "Quote", value: "blockquote" },
      ],
      lists: [{ title: "Bullet", value: "bullet" }],
      marks: {
        decorators: [
          { title: "Strong", value: "strong" },
          { title: "Emphasis", value: "em" },
        ],
        annotations: [
          {
            title: "URL",
            name: "link",
            type: "object",
            fields: [
              {
                title: "URL",
                name: "href",
                type: "url",
              },
            ],
          },
        ],
      },
    }),
    defineArrayMember({
      type: "image",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          type: "string",
          title: "Alternative Text",
        }),
      ],
    }),
  ],
});
```

**Comment by saiichihashimoto** [comment]
So the `config` prop from `NextStudio` comes from `sanity`'s `StudioProps` interface. I tried this:

```typescript
import type { Config as ConfigNative } from "sanity";

type TypedConfig<
  TTypeDefinition extends Type<any, any, any, any, any, any>,
  TPluginTypeDefinition extends Type<any, any, any, any, any, any> = Type<
    string,
    any,
    any,
    any,
    any,
    any
  >
> = Config<TTypeDefinition, TPluginTypeDefinition>;

declare module "sanity" {
  interface StudioProps {
    config: ConfigNative | TypedConfig<any, any>;
  }
}
```

and received this error:

<img width="1000" alt="image" src="https://github.com/saiichihashimoto/sanity-typed/assets/2819256/8250cc7e-1a2e-43b8-9b01-8c6e326b636a">

This isn't doable. Typescript won't let you augment the prop in a way that isn't strictly a subtype, which we definitely aren't. Even any helper functions essentially amount to `defineConfig(...) as SanitysNativeConfig`, which the cast is actually easier than any helper I could provide. There's ultimately no solution that isn't dirty and less usable than a simple cast, so your solution of either doing a `as ConfigNative` or a `@ts-expect-error` is the correct approact.

Closing this.

**Comment by saiichihashimoto** [comment]
@amorfati254 New [`@sanity-typed/next-sanity`](https://github.com/saiichihashimoto/sanity-typed/tree/main/packages/next-sanity) package! Please try it out, I think it addresses your issue, directly. I'm not 100% certain it will solve the `NextStudio` prop, so maybe you can help me test that!

**Comment by amorfati254** [comment]
> @amorfati254 New [`@sanity-typed/next-sanity`](https://github.com/saiichihashimoto/sanity-typed/tree/main/packages/next-sanity) package! Please try it out, I think it addresses your issue, directly. I'm not 100% certain it will solve the `NextStudio` prop, so maybe you can help me test that!

I will try it out today and update you on it.
