### ISSUE TITLE
Fix object array unions

### ISSUE THREAD

**Issue by donalffons** [saiichihashimoto/sanity-typed#119]
Hi and thank you @saiichihashimoto for your fantastic work with this project!

Here is my use case: I have a document named `booklet` that has an array of `sections`. Each section can be either `frontCover` or `textContent`.
```js
// schema.js
const booklet = defineType({
  name: "booklet",
  type: "document",
  fields: [
    defineField({
      name: "sections",
      type: "array",
      of: [
        defineField({
          type: "object",
          name: "frontCover",
          fields: [
            defineField({
              name: "title",
              type: "string",
            }),
          ],
        }),
        defineField({
          type: "object",
          name: "textContent",
          fields: [
            defineField({
              name: "text",
              type: "string",
            }),
          ],
        }),
      ],
    }),
  ],
});
```

Later when I'm using the data, the following doesn't work:
```ts
type Booklet = Extract<SchemaValues, { _type: "booklet" }>;
const myBooklet: Booklet = ...;
// ...
for(const section of myBooklet.sections) {
  if(section._type === "frontCover") {
    console.log(section.title); // Error! Property "title" does not exist
  }
  if(section._type === "textContent") {
    console.log(section.text); // Error! Property "text" does not exist
  }
}
```

Maybe this is related to #96?!

**Comment by donalffons** [comment]
When I inspect that in VS code, the type is not what I would expect...
![image](https://github.com/saiichihashimoto/sanity-typed/assets/33040347/a9cc313b-f21d-446c-bb1c-1544fe97b30c)

**Comment by Michael-Janke** [comment]
It seems that using defineArrayMember is necessary for the members of the array.

**Comment by saiichihashimoto** [comment]
I ran this locally and the way the unions are being constructed is wrong.

This is the type you want for `sections`:
```typescript
      (
        | {
            _key: string;
            _type: "frontCover";
            title?: string;
          }
        | {
            _key: string;
            _type: "textContent";
            text?: string;
          }
      )[]
```

But instead it's this:
```typescript
(({
    title?: string | undefined;
} | {
    text?: string | undefined;
}) & ({
    _key: string;
    _type: "frontCover";
} | {
    _key: string;
    _type: "textContent";
}))[]
```

The derivation of the values and the derivation of the `_type`/`_key` are being union-ed separately and then intersected, when they should be intersected with the values and then union-ed. This is a pretty good test case to use as well. I suspect adding the `_key` is somehow making this happen.

**Comment by saiichihashimoto** [comment]
OK. Typescript ternaries splits types into a union, so I was effectively splitting the type twice and intersecting them, resulting in an intersection of two unions. I needed one ternary that intersected within it, so then I'd have one union with the intersections within it. Confusing distinction, but I've got a fix in flight.

**Comment by donalffons** [comment]
Thanks a ton! Works perfectly, now :slightly_smiling_face:.
