### ISSUE TITLE
`_type` field of arrayMember is unknown

### ISSUE THREAD

**Issue by phmasek** [saiichihashimoto/sanity-typed#134]
Thank you for all the swift replies and fantastic work @saiichihashimoto! The new structure is resolving a lot of the previously encountered problems and is very nice to work with.

Right now the `_type` field of an `arrayMember` is `unknown`.
Would be great to be able to use the `_type` field of an `arrayMember` as a type guard. I've tried to clarify what would be nice to achieve with the code below.

### Schemas
```typescript
const RowSection = defineType({
  title: 'Row',
  name: 'section.row',
  type: 'object',
  fields: [
    defineField({
      name: 'rowText',
      type: 'string'
    })
  ]
});

const ParagraphSection = defineType({
  title: 'Paragraph',
  name: 'section.paragraph',
  type: 'object',
  fields: [
    defineField({
      name: 'paragraphText',
      type: 'string'
    })
  ]
});

const BodyComponent = defineType({
  title: 'Body sections',
  name: 'component.body',
  type: 'array',
  of: [
    defineArrayMember({ type: 'section.row' }),
    defineArrayMember({ type: 'section.paragraph' }),
  ],
});

type Schema = InferSchemaValues<typeof config>;
```

### Implementing
```typescript

/**
 * Expected usage
 */
const body: Schema['component.body'];

body.map((section) => {
  section._type // This is `unknown` instead of `section.row` or `section.paragraph`
});


/**
 * Work around
 * This allows using `_type` field as type guard.
 */
type SectionType = Schema['section.row'] | Schema['section.paragraph'];
type BodyType = SectionType[];

const body: BodyType;

body.map((section) => {
  section._type // This is `section.row` or `section.paragraph`
});
```

**Comment by amorfati254** [comment]
Experencing the same issue when using the `@portabletext/react`  package. Its prop value expects the _type field but you cannot use them since they are unknown in array members. I have tried the _InferValue<typeof schema> but does not work also.

**Comment by saiichihashimoto** [comment]
That's because, I didn't consider how `defineType` will work within an array 🙃

PR incoming
