### ISSUE TITLE
Allow publishing generated types

### ISSUE THREAD

**Issue by saiichihashimoto** [saiichihashimoto/sanity-typed#14]
Migrating from https://github.com/saiichihashimoto/sanity-typed-schema-builder/issues/155 (@mckelveygreg)

For whatever reason, the types that are generated weren't publishable. Might be related to [this issue](https://github.com/microsoft/TypeScript/issues/48212) which was in the 4.8 milestone, but is now in the 5.1.0 milestone.

**Comment by mckelveygreg** [comment]
Thanks for tagging me! I'm literally talking with my co-worker about this issue

**Comment by saiichihashimoto** [comment]
@mckelveygreg is this still an issue? Please re-comment or re-open this if so. I'm trying to cleanup issues and I haven't run into this for a while, and it might not be relevant in `@sanity-typed/types`.
