### ISSUE TITLE
Types for preview

### ISSUE THREAD

**Issue by saiichihashimoto** [saiichihashimoto/sanity-typed#15]
Migrated from https://github.com/saiichihashimoto/sanity-typed-schema-builder/issues/167 (@benjick, @miklschmidt)

Typing the `preview` field. I believe right now it tries some defaults which aren't perfect. It gets a bit strange with the `select`, which ultimately introduces some magic.

**Comment by cereallarceny** [comment]
I could really use this. Currently, the only type errors in my schemas are from previews. Would be happy to help with this if I can @saiichihashimoto.

**Comment by saiichihashimoto** [comment]
Now that `@sanity-typed/types` is mostly ready-to-go, schema-builder is on its way towards deprecation. I think type casting is the only real solution in schema-builder, but #100 addresses this for `@sanity-typed/types`, so I'll close this one.
