### ISSUE TITLE
Could we make `_InferValue` public?

### ISSUE THREAD

**Issue by brendanmoore** [saiichihashimoto/sanity-typed#157]
Is there a specific reason `_InferValue` is considered private? I have a use case where I'd like a library of schema types that could be shared across projects. It appears the only way to expose the inferred type is to to infer from `config` however it would make sense to be able to do that beforehand:

i.e. (in library)
```typescript
// my-entities-lib/blog-post.ts
export const blogPost = defineType({
  title: "Blog post"
  type: "document"
  fields: [
    defineField({
      name: "title",
      type: "string"
    }),
    defineField({
      name: "title",
      type: "string"
    })
    // ...
  ]
});

// Local type inference 👇
export type BlogPost = InferType<typeof blogPost>;
```
Then in a project sanity config
```typescript
// import the schema def 👇
import { blogPost } from "my-entities-lib";

const config = defineConfig({
  schema: {
    types: [blogPost]
  }
});
```
Then in a project client code
```typescript
// import the type 👇
import { BlogPost } from "my-entities-lib";

const BlogPostPage = ({ blogPost }: { blogPost: BlogPost }) => {
  // ...
}
```

**Comment by brendanmoore** [comment]
Okay I see now that we actually need a "world view" in order to enable more complex nested schemas (given how we reference block/field types by `name`). This is both great and annoying. It leads me to believe it may not be possible to have a more "atomic" library for entities.

**Comment by saiichihashimoto** [comment]
Yes, you’re correct as to the why, which is unfortunate. You can export the ‘Values’ from the config file, import them from the entities file, and export the individual type. Even though it’s a circular dependency it should work, because type dependencies and runtime dependencies are separate when considering the loop.

I’m going to close this.
