### ISSUE TITLE
Typing PortableTextBlock Children

### ISSUE THREAD

**Issue by donalffons** [saiichihashimoto/sanity-typed#183]
(From what I can tell), Sanity's block editor has two methods of allowing "custom blocks" in the "block" editor: I call them "paragraph blocks" and ["inline blocks"](https://www.sanity.io/guides/add-inline-blocks-to-portable-text-editor#b07a06d4e79f).

```ts
defineField({
  name: "blockContent",
  type: "array",
  of: [
    defineArrayMember({
      type: "object",
      name: "myParagraphBlock",
      fields: [
        defineField({ name: "name", type: "string" }),
      ],
    }),
    defineArrayMember({
      type: "block",
      of: [
        defineArrayMember({ // using defineField() here would result in another scary typescript error
          name: "myInlineBlock",
          type: "object",
          fields: [
            defineField({ name: "name", type: "string" }),
          ],
        }),
      ],
    }),
  ],
})
```

This displays correctly in Sanity's block editor:
![image](https://github.com/saiichihashimoto/sanity-typed/assets/33040347/97a4f589-f777-4a77-9286-efa559110107)

But unfortunately, it seems like this isn't supported by sanity-typed, yet(?!).
![image](https://github.com/saiichihashimoto/sanity-typed/assets/33040347/26117e2a-c818-4069-b4e7-64ba4a83bbd8)

**Comment by saiichihashimoto** [comment]
You are correct. Blocks scared me so I didn't do it yet.

It is time!

**Comment by donalffons** [comment]
Thanks a ton, @saiichihashimoto! I've just had time to try this out and it's working beautifully. This project is extremely helpful when working with Sanity!

**Comment by saiichihashimoto** [comment]
Amazing! Glad to hear it. I build these things in a bubble, love to hear the feedback 😊
