### ISSUE TITLE
Guess the type of the parameters

### ISSUE THREAD

**Issue by romeovs** [saiichihashimoto/sanity-typed#240]
I can currently write a query like so, without any type errors:

```ts
client.fetch(`*[_type == "user" && username == $username]`, {
  // note the obvious typo here:
  usern___: "romeovs",
})
```

It would be great if we could get the query params that are used in the query and make them required. So in the above example the type for the params argument should be:
```ts
type Params = Exact<{
  username: unknown
}>
```

Even better would be if we could determine the type based on how the param is used (eg. it's being compared to another string in this example, so it should be a string most likely).
The type would then be:
```ts
type Params = Exact<{
  username: string
}>
```

**Comment by saiichihashimoto** [comment]
Deriving the parameters to have an `unknown` type might be possible, although it might add to the typescript complexity, which might not be worth it. Deriving the actual type might actually be impossible. In your example, it is _likely_ to be a string, but not certain, and if gets weirder when we're doing other comparators, like `>` or `in` or if you're comparing the types of two parameters to each other.

**Comment by romeovs** [comment]
I agree about deriving the actual types, since GROQ does not really care for the types anyway.

Do you think it would very hard to add the `unknown` types however, or will it take too much from typescript, since the types are already deeply nested?

**Comment by saiichihashimoto** [comment]
I think that's the approach it'd take. It would likely be similar to `ExecuteQuery` in that it would clean out whitespace, then `Parse`, then traverse the tree to find any of the parameter nodes.

**Comment by saiichihashimoto** [comment]
@romeovs, I tried to accomplish this in https://github.com/saiichihashimoto/sanity-typed/pull/258. I couldn't think of any way that wasn't complicated in a new way besides parsing as usual and traversing the tree to find the `ParameterNode`s to type with. Well, that seems to be too much for typescript. Take a look at that PR and feel free to try and get those tests and build working but, otherwise, I'm going to leave this alone.

**Comment by saiichihashimoto** [comment]
Yeah, this isn't working. I messed with it a bit, but still `groq-js` and `client` are never happy with it. `groq-js` I got to a point where it wasn't complaining, but never `client`, where it'll be the most needed.

If you want it for your own typing of parameters, here you go:

```typescript
import type {
  ExprNode,
  ParameterNode
} from "groq-js";

type QueryParamNames<TNode extends ExprNode> = TNode extends ParameterNode
  ? TNode["name"]
  : TNode extends ExprNode
  ? {
      [Key in keyof TNode]: TNode[Key] extends ExprNode
        ? QueryParamNames<TNode[Key]>
        : never;
    }[keyof TNode]
  : never;

export type QueryParams<TNode extends ExprNode> = Simplify<{
  // @ts-expect-error -- Type of property '...' circularly references itself in mapped type ...
  [Name in QueryParamNames<TNode>]: unknown;
}>;
```
