### ISSUE TITLE
Small queries hitting "Type instantiation"

### ISSUE THREAD

**Issue by magicspon** [saiichihashimoto/sanity-typed#244]
Heyo,

Example repo: https://github.com/magicspon/sanity-typed-ts-error

apps/platform/src/pages/posts/[post].tsx

const post = await client.fetch(postQuery, { slug })
Type instantiation is excessively deep and possibly infinite.ts(2589)

**Comment by saiichihashimoto** [comment]
As mentioned in #242, I think there's an issue where smallish queries in other repos hit this limit even though it doesn't in my local tests. Not sure how to handle this, but should figure something out. I'll rename this issue to reflect this.

**Comment by saiichihashimoto** [comment]
Are you still hitting this issue with the updated versions of everything?

**Comment by magicspon** [comment]
@saiichihashimoto I've not looked tbh. I've started using groqd.
