### ISSUE TITLE
Cannot create `objectNamed` that contains an `array`

### ISSUE THREAD

**Issue by cereallarceny** [saiichihashimoto/sanity-typed#36]
I've been trying to create an `objectNamed` schema that I can use in my documents like this:

```ts
import faq from '../shared/faq';

...
{
  name: 'faq',
  title: 'Page FAQ',
  type: faq.ref()
}
...
```

And while I've been able to use many other `objectNamed` schemas in my documents, I cannot get this one to work. I'm not sure if this is a problem with how I'm writing it, a feature missing in the library, or a bug. I'd love your help getting to the bottom of it. Here's my `objectNamed` for `faq`:

```ts
import { s } from '@sanity-typed/schema-builder';

import wysiwyg from './wysiwyg';

export default s.objectNamed({
  name: 'faq',
  title: 'FAQ',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: s.string(),
    },
    {
      name: 'subtitle',
      title: 'Subtitle',
      type: s.text(),
    },
    {
      name: 'questions',
      title: 'Questions',
      type: s.array({
        of: [
          {
            name: 'question',
            title: 'Question',
            type: s.object({
              fields: [
                {
                  name: 'question',
                  title: 'Question',
                  type: s.string(),
                },
                wysiwyg({
                  name: 'answer',
                  title: 'Answer',
                }),
              ],
            }),
          },
        ],
      }),
    },
  ],
});

// export default defineField({
//   name: 'faq',
//   type: 'object',
//   title: 'FAQ',
//   fields: [
//     defineField({
//       name: 'title',
//       title: 'Title',
//       type: 'string',
//     }),
//     defineField({
//       name: 'subtitle',
//       title: 'Subtitle',
//       type: 'text',
//     }),
//     defineField({
//       name: 'questions',
//       title: 'Questions',
//       type: 'array',
//       of: [
//         defineArrayMember({
//           name: 'question',
//           title: 'Question',
//           type: 'object',
//           fields: [
//             defineField({
//               name: 'question',
//               title: 'Question',
//               type: 'string',
//             }),
//             defineField({
//               name: 'answer',
//               title: 'Answer',
//               type: 'wysiwyg',
//             }),
//           ],
//         }),
//       ],
//     }),
//   ],
// });
```

<img width="1728" alt="Screenshot 2023-05-20 at 11 09 11 AM" src="https://github.com/saiichihashimoto/sanity-typed/assets/1297930/d6d7283e-f54b-4e85-b574-3ffc1d820bd9">

Basically I get a `schema is not a function` error. I've learned from converting other types to the schema builder that I want to perhaps do something like this instead:

```ts
import { s } from '@sanity-typed/schema-builder';

import wysiwyg from './wysiwyg';

export default s.objectNamed({
  name: 'faq',
  title: 'FAQ',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: s.string(),
    },
    {
      name: 'subtitle',
      title: 'Subtitle',
      type: s.text(),
    },
    {
      name: 'questions',
      title: 'Questions',
      ...s.array({
        of: [
          {
            ...s.object({
              fields: [
                {
                  name: 'question',
                  title: 'Question',
                  type: s.string(),
                },
                wysiwyg({
                  name: 'answer',
                  title: 'Answer',
                }),
              ],
            }),
            name: 'question',
            title: 'Question',
          },
        ],
      }),
    },
  ],
});
```

That then returns this error:

<img width="1728" alt="Screenshot 2023-05-20 at 11 21 31 AM" src="https://github.com/saiichihashimoto/sanity-typed/assets/1297930/6d8cd7db-6f4f-4d4d-ba6e-a37c1c572d8e">

I also have a typescript error, but that's the least of my concerns right now. You'll note that I use a field called `wysiwyg`, [which has its own problems that I'll describe in another issue](https://github.com/saiichihashimoto/sanity-typed/issues/37).

**Current typescript error on top-level `fields` array:**

> Type '[{ name: string; title: string; type: SanityType<{ options: (Omit<StringOptions | undefined, "list"> & { list?: [string | { title: string; value: string; }, ...(string | { ...; })[]] | undefined; }) | undefined; ... 7 more ...; placeholder?: string | undefined; }, string, string, string>; }, { ...; }, { ...; }]' is not assignable to type '[FieldOptions<string, ZodTypeAny, unknown, boolean>, ...FieldOptions<string, ZodTypeAny, unknown, boolean>[]]'.
  Type at positions 1 through 2 in source is not compatible with type at position 1 in target.
    Type '{ mock: (faker: Faker, path?: string | undefined) => { _key: string; }[]; parse: (data: unknown) => { _key: string; }[]; resolve: (data: unknown) => { _key: string; }[]; schema: () => { type: string; of: ItemDefinitions[]; ... 6 more ...; icon?: React.ReactNode | React.ComponentType<...>; }; zod: ZodType<...>; zodRe...' is not assignable to type 'FieldOptions<string, ZodTypeAny, unknown, boolean>'.
      Property 'type' is missing in type '{ mock: (faker: Faker, path?: string | undefined) => { _key: string; }[]; parse: (data: unknown) => { _key: string; }[]; resolve: (data: unknown) => { _key: string; }[]; schema: () => { type: string; of: ItemDefinitions[]; ... 6 more ...; icon?: React.ReactNode | React.ComponentType<...>; }; zod: ZodType<...>; zodRe...' but required in type '{ name: string; optional?: boolean | undefined; type: SanityType<Omit<any, NamedSchemaFields>, any, any, unknown>; }'.ts(2322)
index.d.ts(81, 5): 'type' is declared here.
index.d.ts(618, 5): The expected type comes from property 'fields' which is declared here on type '{ description?: string | ReactElement<any, string | JSXElementConstructor<any>> | undefined; title?: string | undefined; options?: ObjectOptions | undefined; ... 13 more ...; preview?: Preview<...> | undefined; }'
(property) fields: [FieldOptions<string, ZodTypeAny, unknown, boolean>, ...FieldOptions<string, ZodTypeAny, unknown, boolean>[]]

**Comment by cereallarceny** [comment]
This is what I ended up with:

```ts
import { s } from '@sanity-typed/schema-builder';
import { UnknownIcon } from '@sanity/icons';

import { wysiwyg } from './';

export default s.objectNamed({
  name: 'faq',
  title: 'FAQ',
  fields: [
    {
      name: 'title',
      title: 'Title',
      type: s.string(),
    },
    {
      name: 'subtitle',
      title: 'Subtitle',
      type: s.text(),
    },
    {
      name: 'questions',
      title: 'Questions',
      type: s.array({
        of: [
          s.object({
            name: 'question',
            title: 'Question',
            preview: {
              select: {
                title: 'question',
              },
              prepare: ({ title }) => ({
                title,
                media: UnknownIcon,
              }),
            },
            fields: [
              {
                name: 'question',
                title: 'Question',
                type: s.string(),
              },
              wysiwyg({
                name: 'answer',
                title: 'Answer',
              }),
            ],
          }),
        ],
      }),
    },
  ],
});
```

However, when using `s.infer<typeof faq>` it produces the wrong type:

```ts
type FAQSharedObject = {
    subtitle: string;
    title: string;
    _type: "faq";
    questions: {
        _key: string;
    }[];
}
```

I've seen this sort of issue in a bunch of places - where anything inside of an array ends up with some `Record<string, string>` looking type. Would love to know if there's a way to do this that produces the intended types, or if we're looking at a bug @saiichihashimoto .

**Comment by saiichihashimoto** [comment]
I mentioned this in another issue, but pretty much all `s.*()` methods return a _type_, not a _field_, and that's a huge distinction. It's the main reason that `s.something({ name, title })` doesn't work (except with select things).

Your `wysiwyg` method (that I think you reference the source for in https://github.com/saiichihashimoto/sanity-typed/issues/37) returns a _field_ instead of a _type_. The problem here is how typescript derives literal strings (ie `"fieldName"`) versus just the type `string`. If you look at the return type of `wysiwyg`, it returns something of type `{ ..., name: string }`. Typescript isn't seeing the name of the field as `"answer"` (or `"wysiwyg"`? Depends on that methods implementation), but as `string`. It's annoying, but if you take the field definition out of being directly inline, you'll have to do `name: 'answer' as const,` and make sure that literal value propagates back out of your `wysiwyg()` method. I would suggest you change the method to return a type instead of a field, so you can do this:

```diff
- wysiwyg({
-   name: 'answer',
-   title: 'Answer',
- })
+ {
+   name: 'answer',
+   title: 'Answer',
+   type: wysiwyg(),
+ }
```

**Comment by cereallarceny** [comment]
@saiichihashimoto I've read your response a few times and can't really figure out what exactly the suggested improvement is. Could you be more specific with a code example? Ignore the `wysiwyg` in your response - I'll work on that next.
