### ISSUE TITLE
@sanity-typed/utils@npm:0.0.0-development: The remote server failed to provide the requested resource

### ISSUE THREAD

**Issue by mckelveygreg** [saiichihashimoto/sanity-typed#362]
Uh oh, looks like `@sanity-typed/utils` didn't get published? 

`@sanity-typed/types@5.7.0` has this as a dependency it looks like, so my installs can't resolve... 

LMK if there is anything I can do to help

**Comment by saiichihashimoto** [comment]
Ah, I was hoping it would bundle it into the build. I'll fix this today.

**Comment by saiichihashimoto** [comment]
For context, I don't want it to be published. I wanted it to get fully bundled into the build, no one needs to consume that library directly. I think I've got a fix ready to go.

**Comment by saiichihashimoto** [comment]
@kodiakhq is aggressive about closing things but, once semantic-release releases the new version (which should be in the next 10 minutes), let me know if this solved your issue!

**Comment by mckelveygreg** [comment]
Thanks!! Installs working! Now back to my regularly scheduled bugz 🐛

**Comment by martinse** [comment]
I'm having the same issue using the latest `@sanity-typed` versions

```
❯ npm ls --depth=5 | grep @sanity-typed
├─┬ @sanity-typed/client@1.9.0
│ ├─┬ @sanity-typed/groq@1.4.7
│ │ ├── @sanity-typed/types@5.8.0 deduped
│ ├── @sanity-typed/types@5.8.0 deduped
├─┬ @sanity-typed/types@5.8.0
```


Error output when building:
```
./node_modules/@sanity-typed/types/src/internal.ts:89:8
Type error: Cannot find module '@sanity-typed/utils' or its corresponding type declarations.

  87 |   MaybeArray,
  88 |   TupleOfLength,
> 89 | } from "@sanity-typed/utils";
     |        ^
  90 |
  91 | // HACK Couldn't use type-fest's Merge >=3.0.0
  92 | type Merge_<FirstType, SecondType> = Except<
```

**Comment by saiichihashimoto** [comment]
Well, @martinse is importing directly from `src` files, not built files, so use-at-your-own-risk-unstable-files-be-there.

I just made [this PR](https://github.com/saiichihashimoto/sanity-typed/pull/406) for also building `internal.ts`, so you can import from `/dist/internal` in the next version but everything in there is still unstable and non-public APIs, so nothing is supported.

**Comment by martinse** [comment]
@saiichihashimoto Fix in new version working! Not sure though if I did something wrong when importing but the error came from within sanity-typed. I followed the tutorial here: https://www.sanity.io/plugins/sanity-typed-types#usage - only thing I changed was to move the `./sanity` folder in to my `src/` folder. Currently the rest of the project is a plain Next.js starter
