### ISSUE TITLE
Cannot create custom `block` type with `annotations` a typescript support

### ISSUE THREAD

**Issue by cereallarceny** [saiichihashimoto/sanity-typed#37]
Instead of doing:

```ts
{
  name: 'wysiwyg',
  title: 'WYSIWYG',
  type: s.array({
    of: [{ s.block() }]
  })
}
```

I wanted to add a few more custom types to all WYSIWYG editors in my Sanity CMS. Namely, I want to add a custom `objectNamed` called `youtube` (code posted below), and an `s.image()` as well. In addition, I wanted to add 3 annotations: highlight, link, and button. I've managed to do all of this, but the way I create a `wysiwyg` editor is awkward and doesn't have complete type support:

1. I couldn't figure out how to get it to be an `objectNamed`. Since it's actually an `array`, and not an `object` to begin with, the `array` function does not expose a `ref`, making this impossible.
2. I could only figure out how to get the `wysiwyg` editor to render when I do this:

```ts
import wysiwyg from '../shared/wysiwyg';

...
wysiwyg({
  name: 'wysiwyg',
  title: 'The editor',
})
...
```

What would be desirable is to address it like any other `objectNamed`:

```ts
import wysiwyg from '../shared/wysiwyg';

...
{
  name: 'wysiwyg',
  title: 'The editor',
  type: wysiwyg.ref()
}
...
```
3. The definition of my `image` and `youtube` types were really awkward. I cannot do:

```ts
{
  name: 'image',
  title: 'Image',
  type: s.image()
},
{
  name: 'youtube',
  title: 'YouTube',
  type: youtube.ref()
}
```

as you would expect. Instead, I need to do:

```ts
{
  ...s.image(),
  name: 'image',
  title: 'Image',
},
{
  ...youtube.ref(),
  name: 'youtube',
  title: 'YouTube',
},
```

This isn't a huge deal, and it works, but it's a big awkward.

4. I could not properly type my annotations. This is what I had to do:

```ts
...
s.block({
  marks: {
    annotations: [
      {
        name: 'highlight',
        title: 'Highlight',
        type: 'color',
        icon: StringIcon,
      },
    ]
  }
})
...
```

Instead of:

```ts
import color from '../shared/color';

...
s.block({
  marks: {
    annotations: [
      {
        name: 'highlight',
        title: 'Highlight',
        type: color.ref()
        icon: StringIcon,
      },
    ]
  }
})
...
```

Here's the full source of the working (but certainly not "correct") WYSIWYG editor:

```ts
import { LinkIcon, StringIcon, UnpublishIcon } from '@sanity/icons';
import { s } from '@sanity-typed/schema-builder';

import youtube from './youtube';

export default (props: any) => ({
  name: 'wysiwyg',
  title: 'WYSIWYG',
  ...props,
  type: s.array({
    of: [
      s.block({
        marks: {
          annotations: [
            {
              name: 'highlight',
              title: 'Highlight',
              type: 'color',
              icon: StringIcon,
            },
            {
              name: 'link',
              title: 'Link',
              icon: LinkIcon,
              type: 'object',
              fields: [
                {
                  name: 'href',
                  title: 'URL',
                  type: 'string',
                },
              ],
            },
            {
              name: 'button',
              title: 'Button',
              icon: UnpublishIcon,
              type: 'object',
              fields: [
                {
                  name: 'link',
                  title: 'Link',
                  type: 'string',
                },
                {
                  name: 'isCentered',
                  title: 'Centered',
                  type: 'boolean',
                },
              ],
            },
          ],
        },
      }),
      {
        ...s.image(),
        name: 'image',
        title: 'Image',
      },
      {
        ...youtube.ref(),
        name: 'youtube',
        title: 'YouTube',
      },
    ],
  }),
});

// export default defineField({
//   name: 'wysiwyg',
//   title: 'WYSIWYG',
//   type: 'array',
//   of: [
//     defineArrayMember({
//       type: 'block',
//       marks: {
//         annotations: [
//           defineField({
//             name: 'highlight',
//             title: 'Highlight',
//             type: 'color',
//             icon: StringIcon,
//           }),
//           defineField({
//             name: 'link',
//             title: 'Link',
//             type: 'object',
//             icon: LinkIcon,
//             fields: [
//               defineField({
//                 name: 'href',
//                 title: 'URL',
//                 type: 'string',
//               }),
//             ],
//           }),
//           defineField({
//             name: 'button',
//             title: 'Button',
//             type: 'object',
//             icon: UnpublishIcon,
//             fields: [
//               defineField({
//                 name: 'link',
//                 title: 'Link',
//                 type: 'string',
//               }),
//               defineField({
//                 name: 'isCentered',
//                 title: 'Centered',
//                 type: 'boolean',
//               }),
//             ],
//           }),
//         ],
//       },
//     }),
//     defineArrayMember({
//       name: 'image',
//       title: 'Image',
//       type: 'image',
//     }),
//     defineArrayMember({
//       name: 'youtube',
//       title: 'YouTube',
//       type: 'youtube',
//     }),
//   ],
// });
```

I would love any help you can provide to get this in a better shape. I'm really committed to this library and am moving all my schemas to it. I'm just facing some problems in the migration.

**Comment by saiichihashimoto** [comment]
`s.objectNamed` is just a sanity object with a `name` (sanity treats named objects slightly different). So the idea of "I couldn't figure out how to get it to be an objectNamed" is because you can't have an object be an array. You can have an array inside of an object or vice versa but array != object so `s.array().ref()` isn't going to resolve into anything valid in native sanity schema land.

You've self identified this, but all the `...s.thing()` should be `type: s.thing()`. Not sure how it's working, but this'll likely produce the wrong types or break going forward.

If you want a reusable type, I'd avoid trying to make `.ref()` work altogether. `.ref()` is effectively so that you can register an object along with your documents and use them via `type: 'myCustomObject'` but, instead of it being a string like it is in native sanity schemas, you can just reference the object directly. But since everything is javascript, you can just reuse the same javascript variables instead, which is a lot easier to understand.

For example:

```
const mySpecialArray = s.array({ of: [whatever] });

const myDocumentType1 = s.document({
  fields: [
    {
      name: 'theArray',
      type: mySpecialArray,
    },
  ],
});
```

I think `.ref()` is really confusing (and I named it weirdly too, especially since something called `reference` also exists). It's truly so sanity could let you make arbitrary object shapes and reuse them in other schemas with `type: 'myCustomObject'` but, since everything is defined with javascript, I think you'll have an easier time just using javascript variables across the board. I think you won't produce values with `_type: 'myCustomObject'` (I need to verify this) but, if you can infer the right typescript types, then I doubt you actually need this anyways.

**Comment by cereallarceny** [comment]
> You've self identified this, but all the ...s.thing() should be type: s.thing(). Not sure how it's working, but this'll likely produce the wrong types or break going forward.

Interestingly enough, I get a type error when doing this. The following code:

```ts
import { LinkIcon, StringIcon, UnpublishIcon } from '@sanity/icons';
import { s } from '@sanity-typed/schema-builder';

import { youtube } from './youtube';

export const wysiwyg = (props = { name: 'wysiwyg', title: 'WYSIWYG' }) => ({
  ...props,
  type: s.array({
    of: [
      s.block({
        marks: {
          annotations: [
            ...
          ],
        },
      }),
      {
        name: 'image', // ts error here
        title: 'Image',
        type: s.image()
      },
      {
        name: 'youtube', // ts error here
        title: 'YouTube',
        type: youtube.ref()
      },
    ],
  }),
});
```

Throws the following error on the `name` property:

> Type '[SanityType<{ type: string; options?: BlockOptions | undefined; validation?: ValidationBuilder<TypedValueRule<SanityBlock<PortableTextMarkDefinition, ArbitraryTypedObject | PortableTextSpan, string, string>>, SanityBlock<...>> | undefined; ... 8 more ...; icon?: ReactNode | ComponentType<...>; }, SanityBlock<...>, S...' is not assignable to type '[SanityType<ItemDefinitions, unknown, unknown, unknown>, ...SanityType<ItemDefinitions, unknown, unknown, unknown>[]]'.
  Type at positions 1 through 2 in source is not compatible with type at position 1 in target.
    Type '{ name: string; title: string; type: SanityType<{ options: { hotspot: boolean; metadata?: ImageMetadataType[] | undefined; storeOriginalFilename?: boolean | undefined; accept?: string | undefined; ... 4 more ...; modal?: { ...; } | undefined; }; ... 11 more ...; fieldsets?: FieldsetDefinition[] | undefined; }, { ......' is not assignable to type 'SanityType<ItemDefinitions, unknown, unknown, unknown>'.
      Object literal may only specify known properties, and 'name' does not exist in type 'SanityType<ItemDefinitions, unknown, unknown, unknown>'.ts(2322)
index.d.ts(402, 5): The expected type comes from property 'of' which is declared here on type '{ options?: ArrayOptions<unknown> | undefined; validation?: ValidationBuilder<ArrayRule<unknown[]>, unknown[]> | undefined; initialValue?: InitialValueProperty<any, unknown[]>; ... 10 more ...; of: [...]; }'

That's exactly why I did it with the object spread `...`. It also produces the following error when saved:

![Screenshot 2023-05-22 at 5 39 00 PM](https://github.com/saiichihashimoto/sanity-typed/assets/1297930/ba726b5d-cb77-4995-87fa-6cd4e25f23e2)

---

Could you maybe provide an example of how you would compose this `wysiwyg` component I've got? This is how I had it before I migrated to `schema-builder`:

```ts
{
  name: 'body',
  title: 'Body',
  type: 'wysiwyg'
}
```

And this is the ideal usage, in my opinion:

```ts
{
  name: 'body',
  title: 'Body',
  type: wysiwyg.ref() // basically the same as if it were an `objectNamed`
}
```

I'm not sure if this is the "Sanity way" of doing things, but my original `type: 'wysiwyg'` worked perfectly fine before I migrated to `schema-builder`. If it shouldn't have, I'd love to better understand why.

This is exactly why I felt that although `wysiwyg` was an array, and not an object, that I should put it inside of `objectNamed` and implement it using `type: wysiwyf.ref()`, because that's exactly what I did for named objects and it seemed to work (despite being an array). Am I making sense @saiichihashimoto ?
