### ISSUE TITLE
Good documentation

### ISSUE THREAD

**Issue by saiichihashimoto** [saiichihashimoto/sanity-typed#376]
I'm not great at documentation. I'm just making this up as I go 🤷

I'd love:

- [ ] A cool site, probably using docusaurus like all the cool kids do
- [ ] github READMEs for the root and packages
- [ ] npmjs READMEs
- [ ] Code samples throughout
- [ ] All of these using the same source for documentation, as much as possible. I don't want to rewrite or copy/paste for each target.

**Comment by saiichihashimoto** [comment]
I don't think I'm going to do this without a lot more traction. The existing documentation (and the videos I'm making) should be enough to use these libraries, as their nature is simple and wraps existing libraries.

**Comment by mrr11k** [comment]
Hi, 
I'm working on a project where I'm using sanity in monorepo (turborepo) setup. Still a lot of work to do there, but further down the road when I've come up with a solution I would like to contribute smth. in that direction. :)
