### ISSUE TITLE
As const shows error when inside `defineArrayMember`

### ISSUE THREAD

**Issue by pedro199288** [saiichihashimoto/sanity-typed#414]
The `as const` needed when pointing to a reference doesn't work when that reference field is an arrayMember. Like this:
```ts
defineField({
      name: 'categories',
      type: 'array',
      title: 'Categories',
      of: [
        defineArrayMember({
          name: 'category',
          type: 'reference',
          to: {
            type: 'category' as const, // <-- typescript error in type
          },
        }),
      ],
    }),
```

It shows this error 
![image](https://github.com/saiichihashimoto/sanity-typed/assets/40956528/4fa82bbf-304e-4ecc-add8-0bbbc7a7c34d)

When the reference field is not inside an array it works fine

**Comment by pedro199288** [comment]
After undoing the changes related to this library I've discovered that I didn't have to put the 'name' property when the reference is inside an array. So maybe the issue is related to that. I will test this better later (have no time now) and let you know of there is actually an issue or it was just my error :)

**Comment by saiichihashimoto** [comment]
https://www.sanity.io/docs/reference-type#to-be04ff05daec

`to` is supposed to be an array, but you're referencing an object. Put it in an array.

**Comment by pedro199288** [comment]
oh what a mistake... thanks for the quick reply! 🙇🏻
