### ISSUE TITLE
Block in object field `Type instantiation is excessively deep and possibly infinite`

### ISSUE THREAD

**Issue by mckelveygreg** [saiichihashimoto/sanity-typed#549]
My schema has a `body` field, that is a sharable `block` type. Having a `block` as a field on an object causes a `Type instantiation is excessively deep and possibly infinite` error. 
Repro: https://github.com/saiichihashimoto/sanity-typed/pull/551

**Comment by saiichihashimoto** [comment]
Just to be sure, it's different than https://github.com/saiichihashimoto/sanity-typed/blob/main/packages/types/src/specific-issues.test.ts#L114?

```typescript
    const config = defineConfig({
      dataset: "dataset",
      projectId: "projectId",
      schema: {
        types: [
          defineType({
            type: "object",
            name: "foo",
            fields: [
              defineField({
                name: "bar",
                type: "array",
                of: [
                  defineArrayMember({
                    type: "block",
                  }),
                ],
              }),
            ],
          }),
        ],
      },
    });
```

**Comment by mckelveygreg** [comment]
Yeah... i guess now that we are dipping into annotations, typescript gets grumpy again 😢

**Comment by saiichihashimoto** [comment]
Once #551 merges, it'll autoclose this ticket. Still, if this specific issue arises (or the zod schema is still not perfect), please reopen or open a new ticket.
