### ISSUE TITLE
Block annotations zod stripping fields

### ISSUE THREAD

**Issue by mckelveygreg** [saiichihashimoto/sanity-typed#559]
I am validating a sanity webhook response. I have an annotation that is an `internalLink` to some other content. 

I have the groq query setup to resolve some data on the referenced document, but those resolutions are getting stripped when zod validates. 

Is there a setting I need to set somewhere in my schema or on the @sanity-typed zod parser to allow those fields to come through?

**Comment by saiichihashimoto** [comment]
No.

The zod parsers _only_ validate against documents and (unfortunately) nothing more or less. Any resolving against other documents (or any groq operations besides returning full documents) won't work against these generated zods.

I had thought of a creating generated zods for groq queries but... its a lot https://github.com/saiichihashimoto/sanity-typed/issues/306

**Comment by saiichihashimoto** [comment]
Are you saying that you don't see `internalLink` after the zod at all? Or that your groq query resolves to the actual referenced document and you're not seeing that document after the zod?

**Comment by mckelveygreg** [comment]
In my snapshot tests, I parse an example webhook response that I would get, and with the zod updates, the `internalLink` field appears to have been stripped after it is validated. 

I should probably make a repro

**Comment by saiichihashimoto** [comment]
Before you do, just double check you're on`@sanity-typed/zod^2.0.0`, preferably on `2.0.1`

**Comment by mckelveygreg** [comment]
Well, perhaps then this is a feature request. I feel like the utility of @sanity-typed/zod gets very limited if it won't let fields passthrough. I think it is good for it to validate the fields it does find, so it makes those type safe, but the nature of groq and sanity is that there are other untyped values floating around that a dev could validate themselves if they want to use them. 

The example being this query:
```
 {
  ...,
  // resolve the first category
  "category": categories[0]->,
  // include the CRUD operation
  "operation": delta::operation(),
  // resolve referenced documents for proper routing
    body[]{
      ...,
      markDefs[]{
        ...,
        _type == "internalLink" => {
          "slug": @.internalLink->slug
        },
        "postType": @.internalLink->_type
    }
  }
}
```
I am able to append `category` and `operation` onto the zod schema and have it validated.
I am able to have a union of different schema's that I can discriminate by `_type`.

But I don't know how to crack open or to override how zod would treat `markDefs`? At the very least I want to keep those fields around, and I wouldn't mind putting together a zod schema to find them? 

--- 1 hour later...
I added this to my schema... it was either this or an `any` 🤷 
```ts
  .and(
    zod
      .object({
        body: zod
          .array(
            zod.object({
              markDefs: zod
                .array(
                  zod
                    .object({
                      _type: zod.string(),
                      _key: zod.string(),
                      href: zod.string().optional(),
                      reference: zod.string().optional(),
                      postType: zod.string().nullable().optional(),
                      slug: zod
                        .object({
                          _type: zod.literal("slug"),
                          current: zod.string(),
                        })
                        .optional(),
                    })
                    .optional()
                )
                .nullable(),
            })
          )
          .nullable(),
      })
      .nullable()
  )
```
