### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by spaaacetoast** [saiichihashimoto/sanity-typed#58]
<img width="742" alt="image" src="https://github.com/saiichihashimoto/sanity-typed/assets/8573878/75831df6-1b41-4789-9ac5-552895ce50e7">

Hi! Love the new approach but i'm running into this issue that I'm not able to solve on my side, do you have any tips/tricks to solve this? I'm guessing that the inferred type needs to be more calculated step by step but with my limited TS knowledge, no idea where to start

One way I solved this in the schema builder was creating multiple named objects and using ref so typescript would comply. I don't see a way of doing that here tho

Happens when using a defineArrayMember inside another defineArrayMember

**Comment by saiichihashimoto** [comment]
I'd love a minimal repro. Hard to talk around without an example. Off the top of my head, `defineArrayMember` shouldn't be directly under another `defineArrayMember`.

![image](https://github.com/saiichihashimoto/sanity-typed/assets/2819256/9a69bb32-2b6b-4432-b374-6b23948cdf56)

Not sure if this is your issue.

**Comment by spaaacetoast** [comment]
Unfortunately abstracting by an object also doesn't solve the issue...

Uploaded a minimal repo for you! https://github.com/spaaacetoast/to-infinity-and-beyond
under `original.ts` and `seperate-array-member.ts` you can find the error

**Comment by spaaacetoast** [comment]
Well I managed to fix this specific issue! Instead of having a `defineArrayMember` -> `defineField` -> `defineArrayMember`
I replaced the first `defineArrayMember` with `defineType` and now it works brilliantly! :)
