### ISSUE TITLE
Array of union breaks but not locally in tests

### ISSUE THREAD

**Issue by oczkowski** [saiichihashimoto/sanity-typed#622]
Hey 👋🏼 

I'm new to Sanity and I'm trying to build a content model with portable text that allows me to upload images and use code blocks.
I have followed sanity's guide to set this up but I quickly realized the responses I was getting from sanity were untyped.

I have explored two solutions in order to get the typed responses.
- I have read the GROQD Docs and found that they have their own instance of zod which supports types for sanity but I wasn't able to use a SanityImage type inside an Array.
- I found this plugin (sanity-typed) which sounds like the best solution for all of my problems because I can have a single source of truth.

Following the [guide I found in the one of the readme's of this project](https://github.com/saiichihashimoto/sanity-typed/blob/9176f8097d0c3d2238d35241de7a9e4b6bd8edeb/packages/react/README.md), I've setup a simple content model without portable text which worked just fine.

I've started facing issues as soon as I tried to mix `block` types with `image` or `code` types.

@saiichihashimoto I've made a small repo that replicates this issue.
I'm running it on OSX M2 Pro using Node v20.9.0

https://github.com/oczkowski/sanity-typed-example-repo
This repo doesn't have the fetching setup as the issue I'm getting is with sanity-typed type when defining the content model

**Comment by saiichihashimoto** [comment]
I'm out of town for a little while; will take a look!

**Comment by saiichihashimoto** [comment]
Sorry for the delay on this! Will take a look soon.

**Comment by saiichihashimoto** [comment]
Portable Text has been one of the more complicated things. It would have been simpler to just leave them as the original type without any of the generics, but that takes all the typing fun out of it.

**Comment by saiichihashimoto** [comment]
Can you explain the issue you're getting? I created a test for your schema and types in #645 and everything seems to work properly.

**Comment by oczkowski** [comment]
Hey @saiichihashimoto thanks for looking into this 👍🏼 

It isn't an issue with the logic, I believe the portable text will work in this setup but the typing fails.
I have pulled an example out of the repository where an image and a block are defined which results in a type error that says "type block is not assignable to type image"
https://github.com/oczkowski/sanity-typed-example-repo/blob/master/sanity/schema/post.ts

<img width="950" alt="image" src="https://github.com/saiichihashimoto/sanity-typed/assets/45343585/9c25ef6f-13bf-4ef4-9a69-2234bb215a24">

**Comment by saiichihashimoto** [comment]
For now, if you change the `type: "image"` and `type: "block"` to `type: "image" as const` and `type: "block" as const` respectively, does the bug go away?

It's very weird that this is appearing for you, but doesn't show up in the tests. A test that can't be repro-ed or automatically run is sure to break. I'm wondering why this is happening for you but tests with multiple types in the array have no issue 🤷

**Comment by saiichihashimoto** [comment]
Also, what version of `sanity`, `@sanity-typed/*`, and `typescript` are you using? Maybe we can narrow some things down.

**Comment by saiichihashimoto** [comment]
I just locally pulled the repo and I'm still uncertain _why_ it's happening here but not when the repo is testing the exact same code.

Either way, here's a temporary fix:

```typescript
// import { defineArrayMember, defineField, defineType } from "sanity";
import {
  defineArrayMember,
  defineField,
  defineType,
} from "@sanity-typed/types";

const image = defineArrayMember({ type: "image" });

const block = defineArrayMember({
  type: "block",
  of: [defineArrayMember({ type: "file" })],
  styles: [
    { title: "Normal", value: "normal" as const },
    { title: "Foo", value: "foo" as const },
  ],
  lists: [
    { title: "Bullet", value: "bullet" as const },
    { title: "Bar", value: "bar" as const },
  ],
  marks: {
    decorators: [
      { title: "Strong", value: "strong" as const },
      { title: "Baz", value: "baz" as const },
    ],
    annotations: [
      defineArrayMember({
        name: "link",
        type: "object",
        title: "Link",
        fields: [
          defineField({
            name: "href",
            type: "string",
            validation: (Rule) => Rule.required(),
          }),
        ],
      }),
      defineArrayMember({
        name: "qux",
        type: "object",
        title: "Qux",
        fields: [
          defineField({
            name: "value",
            type: "string",
            validation: (Rule) => Rule.required(),
          }),
        ],
      }),
    ],
  },
});

/** No changes using defineType, defineField, and defineArrayMember */
export const postContentModel = defineType({
  name: "post",
  type: "document",
  title: "Post",
  fields: [
    defineField({
      name: "content",
      type: "array",
      title: "Content",
      of: [image, block] as [
        typeof image | typeof block,
        ...(typeof image | typeof block)[]
      ],
    }),
  ],
});
```

I'm going to leave the issue open until I figure this one out.

**Comment by saiichihashimoto** [comment]
It doesn't seem to have anything to do with it being a block: for whatever reason, it looks like it's happening with arrays with multiple types in them. Wondering why this isn't more widespread of an issue.

**Comment by saiichihashimoto** [comment]
OK, I found a few things that _should_ solve this for you, longterm @oczkowski. I pulled this repo into my own workspace and ran into the same issues, and I found a few things.

You don't have typescript installed locally in your project, so vscode (which I'm assuming you're using) is picking whatever "global" version of typescript you have going on. Go to `View > Output`, then change the Dropdown for `Output` to `Typescript` (sometimes you can only see it once you've opened a `.ts` file). You'll see which installation of typescript it's using. If your issue is the same as mine, it's picking it from somewhere outside your project and it's likely a version this doesn't work with (currently, `5.2.2` and no higher).

To make your repo work, I had to install `typescript@5.2.2` in your repo and then create a `.vscode/settings.json` in your repo with this:

```json
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```

Even still, your vscode might be persistent with which installation it uses. Even `Developer: Reload Window` doesn't shake it. Open any typescript file (I chose `post.ts`), hit `cmd + shift + p` (or whatever equivalent in windows), and do `Typescript: Select Typescript Version...` and make sure to `Use Workspace Version 5.2.2`. Your errors will vanish! You should see in the typescript output that it's selecting an installation for your project's `node_modules/typescript`. Your errors should vanish.

**Comment by saiichihashimoto** [comment]
I'm going to set all the package's `peerDependencies` to only allow specific typescript versions. It won't get rid of this issue (it won't magically force vscode to pick the right version) but it might give people a hint that something's going on. After that, I'll close this ticket. You can reopen it if these steps don't actually fix it for you.

**Comment by saiichihashimoto** [comment]
A stackoverflow on how to determine (and fix) your issue: https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it
