### ISSUE TITLE
Inferring image asset types

### ISSUE THREAD

**Issue by scottrippey** [saiichihashimoto/sanity-typed#661]
Currently, when my schema references the built-in `image` type, the inferred result is something like:
```
myImage: {
  _type: "image",
  asset: {
    _type: "reference",
    _ref: string,
  }
}
```

This is correct, but it would be great if the asset reference included `[referenced]: "sanity.imageAsset"` too.

The same goes for file assets. 

It's OK if I have to supply my own document types for these assets.

**Comment by saiichihashimoto** [comment]
What version of `@sanity-typed/types` are you using? Because it should not only do that, but `InferSchemaValues` should also return types for `sanity.imageAsset` and `sanity.fileAsset`.

**Comment by saiichihashimoto** [comment]
![image](https://github.com/saiichihashimoto/sanity-typed/assets/2819256/5ceb0829-ed98-49de-8cd6-502a87d3526a)

https://github.com/saiichihashimoto/sanity-typed/blob/9e9338bef13a0610ecab29d40b5a49871f52adc8/packages/types/src/image.test.ts#L10

There's the test and the screenshot showing what you're looking for.

**Comment by saiichihashimoto** [comment]
Should be since https://github.com/saiichihashimoto/sanity-typed/releases/tag/%40sanity-typed%2Ftypes%406.3.0

**Comment by scottrippey** [comment]
Oh man, you're awesome! I haven't updated in a while, sorry. The latest version is working exactly as I wanted, thank you!
