### ISSUE TITLE
Lodash blocks client from being used in middleware

### ISSUE THREAD

**Issue by phmasek** [saiichihashimoto/sanity-typed#680]
I am trying to build a NextJS project with Sanity and Sanity-Typed installed. In the `middleware.ts` I am using the sanity client, namely `@sanity-typed/client`. Unfortunately, due to the implementation of lodash in this library, the build fails. This is the error I get:

```
./node_modules/lodash/lodash.min.js
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime 
Learn More: https://nextjs.org/docs/messages/edge-dynamic-code-evaluation

Import trace for requested module:
./node_modules/lodash/lodash.min.js
./node_modules/lodash/fp.js
./node_modules/@sanity-typed/client/dist/index.js
./sanity/lib/client.ts


> Build failed because of webpack errors
error Command failed with exit code 1.
```

Works fine when using the createClient from `next-sanity` package. Using latest version of the plugin.

**Comment by saiichihashimoto** [comment]
The edge runtime is seriously restricted as to what it can run. Lodash has gotten a few issues on it ([here](https://github.com/lodash/lodash/issues/5525) and [here](https://github.com/lodash/lodash/issues/5394)). Looks like the best solution is to use [`unstable_allowDynamic`](https://nextjs.org/docs/pages/api-reference/edge#unsupported-apis), as this is a lodash and nextjs specific issue and not something I can really solve.
