### ISSUE TITLE
Required validation of custom field with group property fails

### ISSUE THREAD

**Issue by ekkusi** [saiichihashimoto/sanity-typed#709]
I'm facing an odd problem with trying to put groups on fields with custom types. The following code gives a typing error on the "validation" field:

```typescript
import { defineField, defineType } from "@sanity-typed/types";

export const customType = defineType({
  name: "custom",
  type: "object",
  fields: [
    defineField({
      name: "name",
      type: "string",
    }),
  ],
});

export const document = defineType({
  name: "document",
  type: "document",
  groups: [
    {
      title: "Group",
      name: "group",
    },
  ],
  fields: [
    defineField({
      name: "name",
      type: "custom",
      group: "group",
      validation: (rule) => rule.required(),
    }),
  ],
});
```

The error is the following:

`Type '(rule: { [x: string]: any; optional: () => ...; required: (...args: unknown[]) => { [x: string]: any; optional: () => ...; required: ...; warning: (...args: unknown[]) => ...; [required]: true; }; warning: (...args: unknown[]) => ...; [required]: false; }) => { ...; }' is not assignable to type 'ValidationBuilder<false, AliasValue<"custom">, any>'. Type '{ [x: string]: any; optional: () => { [x: string]: any; optional: ...; required: (...args: unknown[]) => ...; warning: (...args: unknown[]) => ...; [required]: false; }; required: (...args: unknown[]) => ...; warning: (...args: unknown[]) => { [x: string]: any; optional: () => ...; required: (...args: unknown[]) => ...' is not assignable to type 'MaybeArray<{ [x: string]: any; optional: () => ...; required: (...args: unknown[]) => { [x: string]: any; optional: () => ...; required: ...; warning: (...args: unknown[]) => ...; [required]: true; }; warning: (...args: unknown[]) => ...; [required]: false; }>'. Type '{ [x: string]: any; optional: () => { [x: string]: any; optional: ...; required: (...args: unknown[]) => ...; warning: (...args: unknown[]) => ...; [required]: false; }; required: (...args: unknown[]) => ...; warning: (...args: unknown[]) => { [x: string]: any; optional: () => ...; required: (...args: unknown[]) => ...' is missing the following properties from type '{ [x: string]: any; optional: () => ...; required: (...args: unknown[]) => { [x: string]: any; optional: () => ...; required: ...; warning: (...args: unknown[]) => ...; [required]: true; }; warning: (...args: unknown[]) => ...; [required]: false; }[]': length, pop, push, concat, and 35 more.`

When I remove the group property from the "name" field, it works as expected and the error goes away. Equally the error goes away if I change the type from "custom" to "string" for example.

Any help appreciated with this.

UPDATE: The same seems to apply to fieldsets

**Comment by saiichihashimoto** [comment]
Confirmed it's only happening on custom fields, looking into it.

**Comment by saiichihashimoto** [comment]
Found a fix (although I still don't quite understand it...). Pushing/deploying now!
