### ISSUE TITLE
Narrow `number`, `string`, and `array`'s value types by what are in `options.list`

### ISSUE THREAD

**Issue by saiichihashimoto** [saiichihashimoto/sanity-typed#78]
https://www.sanity.io/docs/array-type#list-dd1300e422eb
https://www.sanity.io/docs/number-type#list-bddf9327101c
https://www.sanity.io/docs/string-type#33spwYgc

**Comment by SamScott3000** [comment]
@saiichihashimoto FYI I've created a WIP PR for this issue here: #158. Not quite a drag and drop solution because of needing the `as const` in the schema. But is passing all tests.
